name: astral-ty # you probably want to 'snapcraft register <name>'
base: core26 # the base snap is the execution environment for this snap
build-base: devel
adopt-info: ty
summary:  An extremely fast Python type checker and language server, written in Rust.
description: |
  An extremely fast Python type checker and language server, written in Rust.

  # Warning

  ty is in preview and is not ready for production use.

  We're working hard to make ty stable and feature-complete, but until then,
  expect to encounter bugs, missing features, and fatal errors.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

platforms:
  # Just the ones I can test on for now :-)
  amd64:
  arm64:
  riscv64:

parts:
  ty:
    plugin: rust
    rust-channel: stable
    rust-path:
      - ruff/crates/ty
    source: https://github.com/astral-sh/ty.git
    source-branch: main
    source-depth: 0
    source-submodules:
      - ruff
    build-environment:
      # See: https://github.com/lengau/uv-snap/issues/10
      - to arm64:
        - JEMALLOC_SYS_WITH_LG_PAGE: "16"
      - to ppc64el:
        - JEMALLOC_SYS_WITH_LG_PAGE: "16"
    override-build: |
      craftctl default
      craftctl set "version=$(git describe --tags)"

apps:
  ty:
    command: bin/ty
    plugs:
      - home
      - removable-media

